export enum ColorScheme {
  System = "system",
  Dark = "dark",
  Light = "light",
  RusticSunrise = "rustic-sunrise",
  RusticSunset = "rustic-sunset",
  SoftWhisper = "soft-whisper",
  ShadowedEmbrace = "shadowed-embrace",
  CelestialDelight = "celestial-delight",
  DuskSerenade = "dusk-serenade",
  DeepPlum = "deep-plum",
  NightfallNoir = "nightfall-noir",
  PeachesAndCream = "peaches-and-cream",
  TerraCottaDreams = "terra-cotta-dreams",
  CoastalBreeze = "coastal-breeze",
  FairyForest = "fairy-forest",
  SilverTide = "silver-tide",
  GoldenEarth = "golden-earth",
  PaleSerenity = "pale-serenity",
  RetroHour = "retro-hour",
  TealBlossom = "teal-blossom",
  MeadowGlow = "meadow-glow",
  MidnightOrchid = "midnight-orchid",
  CitrusViolet = "citrus-violet",
  DeepSea = "deep-sea",
  SteelAmber = "steel-amber",
  // Steel Amber palette variants (#dddddd, #125d98, #3c8dad, #f5a962)
  SilverNavy = "silver-navy",
  SlateHoney = "slate-honey",
  MistySaffron = "misty-saffron",
  PaleSunset = "pale-sunset",
  WarmSlate = "warm-slate",
  NavyDusk = "navy-dusk",
  DeepAmber = "deep-amber",
  CobaltMist = "cobalt-mist",
  CobaltEmber = "cobalt-ember",
  MidnightGold = "midnight-gold",
  DeepSaffron = "deep-saffron",
  OceanPebble = "ocean-pebble",
  LagoonWarmth = "lagoon-warmth",
  CeruleanMist = "cerulean-mist",
  TealFlame = "teal-flame",
  AquaHoney = "aqua-honey",
  AzureSpice = "azure-spice",
  GoldenCoast = "golden-coast",
  AmberHaze = "amber-haze",
  HarvestNavy = "harvest-navy",
  WarmIndigo = "warm-indigo",
  SunlitOcean = "sunlit-ocean",
  CitrusTide = "citrus-tide",
}

export enum ImagePresets {
  Screen = "screen",
  InstagramSquare = "instagram-square",
  InstagramPortrait = "instagram-portrait",
  InstagramLandscape = "instagram-landscape",
  // InstagramStory = "instagram-story",
  FacebookStandard = "facebook-standard",
  TwitterStandard = "twitter-standard",
  LinkedInStandard = "linkedin-standard",
  TumblrStandard = "tumblr-standard",
}
