export enum ColorScheme {
  System = "system",
  Dark = "dark",
  Light = "light",
  RusticSunrise = "rustic-sunrise",
  RusticSunset = "rustic-sunset",
  SoftWhisper = "soft-whisper",
  ShadowedEmbrace = "shadowed-embrace",
  CelestialDelight = "celestial-delight",
  DuskSerenade = "dusk-serenade",
  DeepPlum = "deep-plum",
  NightfallNoir = "nightfall-noir",
  PeachesAndCream = "peaches-and-cream",
  TerraCottaDreams = "terra-cotta-dreams",
  CoastalBreeze = "coastal-breeze",
  FairyForest = "fairy-forest",
  SilverTide = "silver-tide",
  GoldenEarth = "golden-earth",
  PaleSerenity = "pale-serenity",
  RetroHour = "retro-hour",
  TealBlossom = "teal-blossom",
  MeadowGlow01 = "meadow-glow-01",
  MeadowGlow02 = "meadow-glow-02",
  MeadowGlow03 = "meadow-glow-03",
  MeadowGlow04 = "meadow-glow-04",
  MeadowGlow05 = "meadow-glow-05",
  MeadowGlow06 = "meadow-glow-06",
  MeadowGlow07 = "meadow-glow-07",
  MeadowGlow08 = "meadow-glow-08",
  MeadowGlow09 = "meadow-glow-09",
  MeadowGlow10 = "meadow-glow-10",
  MeadowGlow11 = "meadow-glow-11",
  MeadowGlow12 = "meadow-glow-12",
  MeadowGlow13 = "meadow-glow-13",
  MeadowGlow14 = "meadow-glow-14",
  MeadowGlow15 = "meadow-glow-15",
  MeadowGlow16 = "meadow-glow-16",
  MeadowGlow17 = "meadow-glow-17",
  MeadowGlow18 = "meadow-glow-18",
  MeadowGlow19 = "meadow-glow-19",
  MeadowGlow20 = "meadow-glow-20",
  MeadowGlow21 = "meadow-glow-21",
  MeadowGlow22 = "meadow-glow-22",
  MeadowGlow23 = "meadow-glow-23",
  MeadowGlow24 = "meadow-glow-24",
}

export enum ImagePresets {
  Screen = "screen",
  InstagramSquare = "instagram-square",
  InstagramPortrait = "instagram-portrait",
  InstagramLandscape = "instagram-landscape",
  // InstagramStory = "instagram-story",
  FacebookStandard = "facebook-standard",
  TwitterStandard = "twitter-standard",
  LinkedInStandard = "linkedin-standard",
  TumblrStandard = "tumblr-standard",
}
