export enum ColorScheme {
  System = "system",
  Dark = "dark",
  Light = "light",
  RusticSunrise = "rustic-sunrise",
  RusticSunset = "rustic-sunset",
  SoftWhisper = "soft-whisper",
  ShadowedEmbrace = "shadowed-embrace",
  CelestialDelight = "celestial-delight",
  DuskSerenade = "dusk-serenade",
  DeepPlum = "deep-plum",
  NightfallNoir = "nightfall-noir",
  PeachesAndCream = "peaches-and-cream",
  TerraCottaDreams = "terra-cotta-dreams",
  CoastalBreeze = "coastal-breeze",
  FairyForest = "fairy-forest",
  SilverTide = "silver-tide",
  GoldenEarth = "golden-earth",
  PaleSerenity = "pale-serenity",
  RetroHour = "retro-hour",
}

export enum ImagePresets {
  Screen = "screen",
  InstagramSquare = "instagram-square",
  InstagramPortrait = "instagram-portrait",
  InstagramLandscape = "instagram-landscape",
  // InstagramStory = "instagram-story",
  FacebookStandard = "facebook-standard",
  TwitterStandard = "twitter-standard",
  LinkedInStandard = "linkedin-standard",
  TumblrStandard = "tumblr-standard",
}
