import clsx from "clsx";
import "./globals.css";
import { Crimson_Text, EB_Garamond } from "next/font/google";

const crimson_text = Crimson_Text({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-crimson-text",
});

const eb_garamond = EB_Garamond({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-eb-garamond",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="theme-light">
      <body
        className={clsx(
          crimson_text.variable,
          eb_garamond.variable,
          "bg-background"
        )}
      >
        <main className="flex min-h-screen flex-col items-center p-4 md:p-18 lg:p-24">
          {children}
        </main>
      </body>
    </html>
  );
}
