import clsx from "clsx";
import "./globals.css";
import {
  Josefin_Sans,
  Crimson_Text,
  Oleo_Script_Swash_Caps,
  Pinyon_Script,
  Petit_Formal_Script,
  EB_Garamond,
} from "next/font/google";

const josefin_sans = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-josefin-sans",
});

const crimson_text = Crimson_Text({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-crimson-text",
});

const oleo_script_swash_caps = Oleo_Script_Swash_Caps({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-oleo-script-swash-caps",
});

const pinyon_script = Pinyon_Script({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-pinyon-script",
});
const petit_formal_script = Petit_Formal_Script({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-petit-formal-script",
});

const eb_garamond = EB_Garamond({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-eb-garamond",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="theme-dark">
      <body
        className={clsx(
          josefin_sans.variable,
          crimson_text.variable,
          oleo_script_swash_caps.variable,
          pinyon_script.variable,
          petit_formal_script.variable,
          eb_garamond.variable,
          "bg-background"
        )}
      >
        <main className="flex min-h-screen flex-col items-center p-4 md:p-18 lg:p-24">
          {children}
        </main>
      </body>
    </html>
  );
}
